### ISSUE TITLE
Can this be used to pull lowest server load?

### ISSUE THREAD

**Issue by andyktaylor** [vashishkov/firewalla-nordlynx#3]
Loving what you build here, as per your comments about the fast/lowest load server not working, I did some research and found this rather awesome github project also: https://github.com/mustafachyi/NordVPN-WireGuard-Config-Generator
On the github page, they have a tool to pull down the Wireguard configs, but also a website that refreshes and can be sorted by server load ( https://nord-configs-crafter.pages.dev/)

How easy would it be to repoint your nordlynx.js to pull from the website or even run the proxy_fetcher.py tool directly on the Firewalla?

**Comment by vashishkov** [comment]
Sure, they just pull complete server list here: 
`https://corsproxy.io/?https://api.nordvpn.com/v1/servers?limit=7000&filters[servers_technologies][identifier]=wireguard_udp`
will implement this on weekends

**Comment by andyktaylor** [comment]
nice one, looking forward to the enhancement ;)

**Comment by vashishkov** [comment]
Now, the profile rotation logic should check the server load, and I've also added a --force command-line argument to forcibly rotate profiles

**Comment by andyktaylor** [comment]
Seems to be working well so far, thanks
